// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADmIuuKzL9GmjTxW7dta8Ht4YshAR6osY',
    appId: '1:561142383587:web:5e605e568a71e89cb296d6',
    messagingSenderId: '561142383587',
    projectId: 'cloud-58782',
    authDomain: 'cloud-58782.firebaseapp.com',
    storageBucket: 'cloud-58782.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaU2KtHP_FHiP0V7arhs6y7HNTdRX5G2k',
    appId: '1:561142383587:android:070d62e3aca8d3fab296d6',
    messagingSenderId: '561142383587',
    projectId: 'cloud-58782',
    storageBucket: 'cloud-58782.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL5WswcFzfUBXnK93zEketgjnu1-bNgM0',
    appId: '1:561142383587:ios:483751af6beb5fdeb296d6',
    messagingSenderId: '561142383587',
    projectId: 'cloud-58782',
    storageBucket: 'cloud-58782.appspot.com',
    iosBundleId: 'com.example.flutterCourseUpdatedMaster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL5WswcFzfUBXnK93zEketgjnu1-bNgM0',
    appId: '1:561142383587:ios:ed48849e3f008b6ab296d6',
    messagingSenderId: '561142383587',
    projectId: 'cloud-58782',
    storageBucket: 'cloud-58782.appspot.com',
    iosBundleId: 'com.example.flutterCourseUpdatedMaster.RunnerTests',
  );
}
